### ISSUE TITLE
GitHub Basics Courses to be completed.

### ISSUE THREAD

**Issue by garylgreer** [garylgreer/treehouse#2]
**ToDo**
_Courses left to complete the GitHub Basics Course Track._

- [x] Create a Branch

- [ ] Create a Branch Test

- [ ] Open a pull request

- [ ] Conflict resolution

- [ ] Review:  Working by Yourself
